version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public
            - ./storage/app:/var/www/html/storage/app:cached
            - ./storage/nginx-logs:/var/log/nginx
            - ./infrastructure/local/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            -   php-fpm
        container_name: gdp_nginx
        networks:
            - gdp_network

#    ngrok:
#        container_name: gdp_ngrok
#        ports:
#            - "0.0.0.0:4040:4040"
#        image: wernight/ngrok
#        environment:
#            - NGROK_AUTH=2KimxVsCHvhbX8W0NRX7yEyX9TB_5REwMx9tGJZomrKvBBRNY
#            - NGROK_REGION=eu
#            - NGROK_PORT=nginx:80
#            - NGROK_HEADER=rewrite
#        networks:
#            - gdp_network

    php-fpm:
        build:
            context: .
            dockerfile: infrastructure/local/docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www
        container_name: gdp_php-fpm
        depends_on:
            -   mysql
        networks:
            - gdp_network

    mysql:
        image: mysql:8.0.31
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gdp
            - MYSQL_USER=gdp
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - ./storage/mysql-image-data:/var/lib/mysql:cached
        networks:
            - gdp_network
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: gdp_mysql

networks:
    gdp_network:
        driver: bridge

