version: '3.8'

services:
    mysql:
        image: mysql:8.0.31
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gdp
            - MYSQL_USER=gdp
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - ./storage/mysql-image-data:/var/lib/mysql:cached
        networks:
            - gdp_network
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: gdp_mysql

    octane:
        build:
            context: .
            dockerfile: infrastructure/local/docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www
        container_name: gdp_octane
        ports:
            - "8080:8080"
        depends_on:
            - mysql
        command: php artisan octane:start --host=0.0.0.0 --port=8080 --watch
        networks:
            - gdp_network

    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public
            - ./storage/app:/var/www/html/storage/app:cached
            - ./storage/nginx-logs:/var/log/nginx
            - ./infrastructure/local/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - octane
        container_name: gdp_nginx
        networks:
            - gdp_network

    redis:
        image: redis:latest
        container_name: gdp_redis
        networks:
            - gdp_network
        ports:
            - 6379:6379

    queue-worker:
        build:
            context: .
            dockerfile: infrastructure/local/docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www
        command: php artisan queue:work
        container_name: gdp_worker
        networks:
            - gdp_network
        depends_on:
            - octane
            - mysql
            - redis

networks:
    gdp_network:
        driver: bridge

